services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ..:/workspace:cached
      - $HOME/.ssh/:/home/vscode/.ssh/
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
