services:
  dev:
    image: mcr.microsoft.com/playwright/python:v1.58.0-noble
    volumes:
      - ..:/workspace:cached
      - $HOME/.ssh/:/home/vscode/.ssh/
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
