name: ci

on:
  push:
    branches: [ "main" ]
  schedule:
  - cron:  '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Dev Container Build and Run Action
      uses: devcontainers/ci@v0.3.19000003
      with:
        imageName: ghcr.io/its3mile/ncsc-caf-scraper-devcontainer
        cacheFrom: ghcr.io/its3mile/ncsc-caf-scraper-devcontainer
        push: always
        runCmd: 
            .venv/bin/python main.py

