name: ci

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 2 * * *'
  push:
    branches: [ "main", "feat/github-actions" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
      
    - name: Dev Container Build and Run Action
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/its3mile/ncsc-caf-scraper-devcontainer
        cacheFrom: ghcr.io/its3mile/ncsc-caf-scraper-devcontainer
        push: never
        runCmd: 
            .venv/bin/python main.py
            
    - run: '[ -f output.json ]' 
    - run: '[ -f output.log ]' 
    
    - run: |
        DATETIME=$(date +"%FT%H%M%S")
        OUTPUT_JSON="NCSC-CAF-${DATETIME}.json"
        mv output.json $OUTPUT_JSON
        echo "OUTPUT_JSON=$OUTPUT_JSON" >> $GITHUB_OUTPUT
        OUTPUT_LOG="NCSC-CAF-${DATETIME}.log"
        mv output.log $OUTPUT_LOG
        echo "OUTPUT_LOG=$OUTPUT_LOG" >> $GITHUB_OUTPUT
      id: set_outputs

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.set_outputs.outputs.output_json }}
        path: ${{ steps.set_outputs.outputs.output_json }}

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.set_outputs.outputs.output_log }}
        path: ${{ steps.set_outputs.outputs.output_log }}
