name: ci

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 2 * * *'
  push:
    branches: [ "main", "feat/github-actions" ]


env:
  APP_DIR: /app
  RELEASE_TAG_SLUG: ${{ github.run_id }}_${{ github.run_attempt }}
  WEB_SCRAPER_NAME: ncsc-caf-scraper

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Web Scraper Container Image Build
        uses: docker/build-push-action@v7
        with:
          push: false
          tags: ${{ github.actor }}/${{ env.WEB_SCRAPER_NAME }}:latest
          build-args: 
            APP_DIR=${{ env.APP_DIR }}

      - name: Run Web Scraper Container
        run: | 
            docker run \
            --name ${{ env.WEB_SCRAPER_NAME }} \
            ${{ github.actor }}/${{ env.WEB_SCRAPER_NAME }}:latest
            
      - name: Extract Web Scraper Output Files
        run: |
          docker cp ${{ env.WEB_SCRAPER_NAME }}:${{ env.APP_DIR }}/output.json NCSC-CAF-${{ env.RELEASE_TAG_SLUG }}.json
          docker cp ${{ env.WEB_SCRAPER_NAME }}:${{ env.APP_DIR }}/output.log NCSC-CAF-${{ env.RELEASE_TAG_SLUG }}.log
          echo "OUTPUT_JSON=NCSC-CAF-${{ env.RELEASE_TAG_SLUG }}.json" >> $GITHUB_OUTPUT
          echo "OUTPUT_LOG=NCSC-CAF-${{ env.RELEASE_TAG_SLUG }}.log" >> $GITHUB_OUTPUT
        id: extract_outputs

      - name: Upload Web Scraper Output Json
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.extract_outputs.outputs.output_json }}
          path: ${{ steps.extract_outputs.outputs.output_json }}
        
      - name: Upload Web Scraper Output Log
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.extract_outputs.outputs.output_log }}
          path: ${{ steps.extract_outputs.outputs.output_log }}
      
      - name: Create Release With Artefacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG_SLUG }}
          files: |
            ${{ steps.extract_outputs.outputs.output_json }}
            ${{ steps.extract_outputs.outputs.output_log }}
