name: ci

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 2 * * *'
  push:
    branches: [ "main", "feat/github-actions" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Dev Container Build and Run Action
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/its3mile/ncsc-caf-scraper-devcontainer
        cacheFrom: ghcr.io/its3mile/ncsc-caf-scraper-devcontainer
        push: always
        runCmd: 
            .venv/bin/python main.py

